# Use a lightweight base image with XRAY installed
FROM alpine/curl:latest as downloader

# Download the latest Xray Core
ENV XRAY_VERSION v1.8.6  # Can be updated to latest stable version
RUN wget -q "https://github.com/XTLS/Xray-core/releases/download/${XRAY_VERSION}/Xray-linux-64.zip" -O /tmp/xray.zip \
    && unzip -q /tmp/xray.zip -d /usr/local/bin \
    && rm /tmp/xray.zip \
    && chmod +x /usr/local/bin/xray

# --------------------------------------------------------------------------

FROM alpine:latest
LABEL maintainer="ahlflk"

# Install necessary packages (curl for health check, ca-certificates for TLS)
RUN apk update && apk add --no-cache curl ca-certificates tzdata

# Copy Xray executable from the downloader stage
COPY --from=downloader /usr/local/bin/xray /usr/local/bin/

# Copy the generated config file and entrypoint script
# The config.json will be generated by your bash script before building
COPY config.json /usr/local/etc/xray/config.json

# Expose the port (Cloud Run requires 8080 by default)
ENV PORT 8080
EXPOSE 8080

# Xray runs with the config file, listening on 8080
# The command uses 'exec' to ensure Xray is PID 1, allowing proper signal handling in Cloud Run.
CMD ["/usr/local/bin/xray", "-config", "/usr/local/etc/xray/config.json"]

# Health Check Command (Optional but good practice)
# You can uncomment this if needed, but Cloud Run uses its own health check.
# HEALTHCHECK CMD curl --fail http://127.0.0.1:8080/ || exit 1
