# 1. Base Image: Use lightweight Alpine Linux
FROM alpine:3.18

# 2. Set environment variable for Xray configuration location
ENV XRAY_LOCATION /usr/local/etc/xray

# 3. Install required packages (curl for download, ca-certificates for TLS)
RUN apk update && \
    apk add --no-cache curl ca-certificates && \
    rm -rf /var/cache/apk/*

# 4. Download, extract, and install the Xray binary
# Downloads the latest Xray-linux-64.zip
RUN curl -L -H "Cache-Control: no-cache" -o /tmp/xray.zip https://github.com/XTLS/Xray-core/releases/latest/download/Xray-linux-64.zip && \
    unzip /tmp/xray.zip -d /tmp/xray && \
    mv /tmp/xray/xray /usr/local/bin/xray && \
    chmod +x /usr/local/bin/xray && \
    rm -rf /tmp/xray*

# 5. Copy the generated 'config.json' into the container
# This config.json is generated by your Bash Script from the .tmpl files.
RUN mkdir -p ${XRAY_LOCATION}
COPY config.json ${XRAY_LOCATION}/config.json

# 6. Expose the port Cloud Run listens on (8080)
EXPOSE 8080

# 7. Command to run when the container starts
CMD ["/usr/local/bin/xray", "-c", "/usr/local/etc/xray/config.json"]
